language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: YuJKZFUZFCfzpAdCNt08JCakiMBO7zPtwB+mKf0LLU9yUFQCYLAQV6CuQ+M7QnE76Vni7Uh8sMyLeAzesuZfx8aWKy38pH5kyfIXy4d5lU4/opX12iYBFOqXhrEnxFMrrYrXh49PsE9vfSSgCyBuhuDvAjs62BsJ7AEyuNRyAy+uY3A8u1ePx/Q6Wh7yH0rJi1ohQn+Vn4Sn31AAs220CxfNGfq2OaIeZ6sMzj2yyEdP/fbz/jdU91ySz4JFXe74fGqfrBQbzsepjm9YJ2pEy/R2YeNJ03DDit7TC5d2o2i8NEhN5u22g3yQfOc1qunxsPcIAF8/3yjUfxoXawwSVSMsm0pRxx5lZUv9OSqoTcSyMImEyVz8HiqQYGwvclDWT2zpazcPIL4hm6JjZ5U2Tch3muLnR16LRCA4QG5To01MJ7cAUu+fr+JYFfh0jmh9Z6h+eT7qc8NsdZZRaOW7kYMGBgDKUBuUVbPADd2tjmNXRvOImUpaqoKr/1PHkHaEUZkRUOnthQc0alc989DnqagS02JXNm7MUMO72ZjtgfemSQUJbvrgrmCS7Cb4IqCC1Jw33kJdr+2pHUGOxNe1wEvuM/m5PPzkSq+1yCNONeQWK7hjjvr6Gg0O3wBDGggMVkYLk/4AR4Sr5s/ijPhGXGi2atFc2PwCXTc/CEkYZ+U=
  app: projetgespizza
  on:
    repo: bdaris/ProjetGespizza

env:
  global:
    - CC_TEST_REPORTER_ID=43b8918e54df85418f54034cc3f74b72ef78137e1c218be283f48cfa90dec54b
language: ruby
rvm:
  - 2.2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
