language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: A2n35Zpj9SbeaVqneRtwbTbJHSdDSVoUYkimfmuEYEGyle2a1hrgqk6nLKezECEwHE6jYJZb9Bjb6LUr2LC0fiLO+z23D5xEHwBadL93tS7qRNG9XNqnJdfkaG5RD0NwtO5Zknj7GvYWMObMIEqSqHI07qjb3cNOGBY8S3T6RO0QPNuyyBZ4Ne1JQs82eFknW3MqwZJ7x7/okanQLENRbMsw2uGpO2rPgk0E/l59G7rwiMymW2xSC2lEH9RobGkyb9jHaQB6SVDWvfda/4KiWKy+l69ZZwDoy6PK83rU/UQhC504J4h5NPgxBF3Z9g/hATdeQNw80+GuIbb3BF2Hbtgikh4dDzA51t3POP7vWTYvGOLZM3YIE5uIsPrh9niWjdBbllAbPYeartx3l3nM7vFYpX+XkyldVAoZD6aP48TTYvBREDHfLiYuQdWOgz+m4FP8nl9In5raxi/oGlfy9vhgmbSsuqwudhXccdsVIpUEslNrmVcpQC5PO0NcrYeeV1awAGBMGJs5iAfIWdpBrjAsEZdOy+1xDaKSpXS4uLSYopfSQiJOSW8WUAjyRKhvzaXPTuOGJGzGGe6QOUkqwgb88AAtnE3u8cj8nQlmTCHZSlLnbv24UYiJzQt81wOtcO2TGKe5V4/TxL69U4l4LfJjoLBjqIZxCCPp+ETzSlw=
  app: projetgespizza
  on:
    repo: bdaris/ProjetGespizza
