language: ruby
rvm:
- 2.5.1
deploy:
  provider: heroku
  api_key:
    secure: KZpc/fmQGZo8OnJ/8beYrZrCbfZAad2fW0iMTIIJquQlUECP94CgFb83taUaTkRX0cW0lfc21k+Us5Uo87z/qcv7GEK7LLlM56RqQs5CwsUcX0OCcTSHK1NoThuM6DkqfWAix3WbZVos0mzDgUfbLEPseOglzIT8FSkIqH2+GGsFRQ0jaKpjp1IYGGtR81+76pr11mALu4awFV8hvRlbjE85uvcd+NoMTp3DFp5NtdfHV5jt4QuEa3TLNa18O0ePJnqT13LMIQkfCqT+fOboYdXS/fio4GRFoW6EeUNSybXY+5pIT6lwbpkH6KmQjRLp23NizjedTXaiEQJo6l9d1UeZ/Epbwxi34Csgf4M+crd1Xs4qFzw6J/+DAK4183+xZ/KmDiORKQDsHodO0wL9YwhTOiHB9WsH2qkr11RIzA3y/ZAFNSp2YRz8SBBahFUL0XvAs4zDcaIZaEW/b/ptj4CYyW6/v5gqDon5OFuDMsyML6puDAjkMPrcrcJf5bltQZlmdVrKBemop5Z13i8TXdIYyMyQdlmhaWE4hCZ23zS8edQ3F2YQVtpePOdQ8n3PAzZ9VNQ2own3KeknAJ9kMnASfQQjojJSyoxseMhSAN3ra02eAPvhgVih4/NreLf1r4bVyzLhtGsZZQXzfD0bG2RFb0I95EwnhRSPqcg8trM=
  app: projetgespizza
  on:
    repo: bdaris/ProjetGespizza
